url: "https://refugiopinheirobeirario.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Refúgio Pinheiro Beira Rio" # the name of your site, e.g. ACME Corp.
lang: "pt-BR"
collections:
  casas:
    output: true
